.build_template: &build_template
  script:
    - npm install
    - npm run build

image: node:16-slim

cache:
  - key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  - key:
      files:
        - components/Styling/package-lock.json
    paths:
      - components/Styling/node_modules

build:
  only:
    - merge_requests  
  <<: *build_template    

pages:
  only:
    - main
  artifacts:
    paths:
      - public
  <<: *build_template
