name: Build and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            components/Styling/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json', 'components/Styling/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install
          cd components/Styling && npm install
        
      - name: Build
        env:
          PLAUSIBLE_PAGE_ID: ${{ secrets.PLAUSIBLE_PAGE_ID }}
        run: |
          if [ -z "$PLAUSIBLE_PAGE_ID" ]; then
            echo "ERROR: PLAUSIBLE_PAGE_ID is not set in GitHub secrets"
            exit 1
          fi
          echo "Building with Plausible page ID configured..."
          npm run build

      - name: Verify Build Output
        run: |
          if [ ! -f "public/js/main.js" ]; then
            echo "ERROR: JavaScript bundle not found at public/js/main.js"
            exit 1
          fi
          if grep -q "pageID" public/js/main.js; then
            echo "✓ Plausible pageID found in JavaScript bundle"
          else
            echo "ERROR: pageID not found in bundle"
            exit 1
          fi

      - name: Validate HTML
        run: npx htmlhint "public/**/*.html"

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
